# Generated by Django 5.2.6 on 2025-11-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('1', 'Player 1'), ('2', 'Player 2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='active_player',
            field=models.CharField(choices=[('1', 'Player 1'), ('2', 'Player 2')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('tie', 'Tie')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
